
#ifndef EXAMPLE_HOT_RELOAD_LIB_EXPORT_H
#define EXAMPLE_HOT_RELOAD_LIB_EXPORT_H

#ifdef EXAMPLE_HOT_RELOAD_LIB_STATIC_DEFINE
#  define EXAMPLE_HOT_RELOAD_LIB_EXPORT
#  define EXAMPLE_HOT_RELOAD_LIB_NO_EXPORT
#else
#  ifndef EXAMPLE_HOT_RELOAD_LIB_EXPORT
#    ifdef example_hot_reload_lib_EXPORTS
        /* We are building this library */
#      define EXAMPLE_HOT_RELOAD_LIB_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define EXAMPLE_HOT_RELOAD_LIB_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef EXAMPLE_HOT_RELOAD_LIB_NO_EXPORT
#    define EXAMPLE_HOT_RELOAD_LIB_NO_EXPORT 
#  endif
#endif

#ifndef EXAMPLE_HOT_RELOAD_LIB_DEPRECATED
#  define EXAMPLE_HOT_RELOAD_LIB_DEPRECATED __declspec(deprecated)
#endif

#ifndef EXAMPLE_HOT_RELOAD_LIB_DEPRECATED_EXPORT
#  define EXAMPLE_HOT_RELOAD_LIB_DEPRECATED_EXPORT EXAMPLE_HOT_RELOAD_LIB_EXPORT EXAMPLE_HOT_RELOAD_LIB_DEPRECATED
#endif

#ifndef EXAMPLE_HOT_RELOAD_LIB_DEPRECATED_NO_EXPORT
#  define EXAMPLE_HOT_RELOAD_LIB_DEPRECATED_NO_EXPORT EXAMPLE_HOT_RELOAD_LIB_NO_EXPORT EXAMPLE_HOT_RELOAD_LIB_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef EXAMPLE_HOT_RELOAD_LIB_NO_DEPRECATED
#    define EXAMPLE_HOT_RELOAD_LIB_NO_DEPRECATED
#  endif
#endif

#endif /* EXAMPLE_HOT_RELOAD_LIB_EXPORT_H */
